### ISSUE TITLE
Ça Snatch pas ..

### ISSUE THREAD

**Issue by maxcore** [djoole/couchpotato.provider.HDO#1]
Je sais pas si c’est les problèmes que le site on eu mais je snatch aucune releases avec le plug in avec mes tests . J’ai mis le dernier Hobbits et pourtant il est sur le site … dans la config j’ai juste coché VO pour qu’il ignore les VO . Sur tout les autre provider , FNT ,LBT ,T411 il snatch la release. J’ai aucune erreur dans les logs .J’ai mis des filtres pour qui prenne seulement les releases avec le mot : French,Multi,truchfrench,fr,VFQ,QC,MULTi-VF2. J’ai essayé sans un mots requis et j’ai un problème de ‘Size’ . Toi il est configurer comment ton couchpotato pour Snatcher tes releases ? Car à voir les releases dans les logs le nom de la releases son très bizarre ..

```
04-18 21:23:48INFO[hpotato.core.plugins.base] Opening url: get https://hd-only.org/ajax.php?action=torrent&id=3353, data: []
04-18 21:23:50DEBUG[hpotato.core.plugins.base] Setting cache 953f1de46751c51edbe6b5241bd0d728
04-18 21:23:50DEBUG[                   hdonly] Torrent added to results : id 3353; name Le Hobbit : La Bataille des Cinq Arm&eacute;es.2014.1080p.Blu-Ray Rip.x265; url https://hd-only.org/torrents.php?action=download&id=3353&authkey=***************j&torrent_pass=*********; detail_url https://hd-only.org/ajax.php?action=torrent&id=3353; size 5413; seeders 42; leechers 0
04-18 21:23:50DEBUG[tato.core.plugins.quality] Found 1080p via identifier 1080p in Le Hobbit : La Bataille des Cinq Arm&eacute;es.2014.1080p.Blu-Ray Rip.x265
04-18 21:23:50DEBUG[tato.core.plugins.quality] Found 1080p via release size: 4000.0 MB < 5413.0 MB < 40000.0 MB
04-18 21:23:50DEBUG[tato.core.plugins.quality] Found 720p via release size: 3000.0 MB < 5413.0 MB < 10000.0 MB
04-18 21:23:50DEBUG[tato.core.plugins.quality] Found brrip via release size: 700.0 MB < 5413.0 MB < 7000.0 MB
04-18 21:23:50DEBUG[tato.core.plugins.quality] Found dvdr via release size: 3000.0 MB < 5413.0 MB < 10000.0 MB
04-18 21:23:50DEBUG[hpotato.core.plugins.base] Setting cache [u'Le Hobbit : La Bataille des Cinq Arm&eacute;es.2014.1080p.Blu-Ray Rip.x265']
04-18 21:23:50INFO[core.media.movie.searcher] Wrong: "Le Hobbit : La Bataille des Cinq Arm&eacute;es.2014.1080p.Blu-Ray Rip.x265" is too small to be BR-Disk. 5413MB instead of the minimal of 20000MB.
04-18 21:23:50DEBUG[hpotato.core.plugins.base] Waiting for hdonly, 1 seconds
04-18 21:23:51INFO[hpotato.core.plugins.base] Opening url: get https://hd-only.org/ajax.php?action=torrent&id=3373, data: []
04-18 21:23:53DEBUG[hpotato.core.plugins.base] Setting cache 23e1bc20328ad2c5a1390a066e68be9e
04-18 21:23:53DEBUG[                   hdonly] Torrent added to results : id 3373; name Le Hobbit : La Bataille des Cinq Arm&eacute;es.2014.1080p.Blu-Ray Rip.x265; url https://hd-only.org/torrents.php?action=download&id=3373&authkey=*********&torrent_pass=*******l; detail_url https://hd-only.org/ajax.php?action=torrent&id=3373; size 14904; seeders 18; leechers 2
04-18 21:23:53INFO[core.media.movie.searcher] Wrong: "Le Hobbit : La Bataille des Cinq Arm&eacute;es.2014.1080p.Blu-Ray Rip.x265" is too small to be BR-Disk. 14904MB instead of the minimal of 20000MB.

```

**Comment by djoole** [comment]
Je ne vois pas de dysfonctionnement, mais voici quelques explications pour que tu comprennes pourquoi ça n'a pas snatché : 
- l'option VO que tu as coché fait le contraire de ce que tu penses, ça ne téléchargera que des torrents qui contiennent au moins le track VO (donc si tu veux de la VF il faut cocher VF)
- le release_name sous HDO ne contient pas la langue, donc si tu configures CP pour qu'il ne récupère que des release qui contiennent VF, TRUEFRENCH, etc, il ne trouvera rien.
- de ce que disent les logs, tu as mis comme qualité BR-disk, hors la release trouvée fait 5GB.
  J'ai vérifié sur HDO, celle qui fait 5GB est en x265, tu n'aurais pas coché x265 par hasard?

**Comment by djoole** [comment]
@maxcore Je pense que tu utilises le fork de Sakara car le title du film que tu as cherché est en français (pas possible dans le CP de ruudburger).

Mon provider est fait pour fonctionner avec le CP de ruudburger, du coup, j'ai une problématique : 
lorsque CP cherche un film, il va faire la recherche sur le titre original, pas le titre français.
Hors, HDO ne donne que le titre FR dans sa BDD. Du coup, moi par exemple je ne peux pas trouver le hobbit la bataille...

Il faudrait que je trouve une API qui permette de récupérer le titre FR à partir du titre original... Si tu as une piste je suis preneur..

Sinon, je vais faire un commit qui explicite plus les options pour ce que soit plus clair, et je fais une modif sur la discrimination au niveau des langues (pour que le MULTI soit pris en compte au niveau des options VF et VO) et je rajoute également une option MULTI.

**Comment by djoole** [comment]
J'ai fait les modifs, donc pour résumer : 
- n'active pas de liste de mots-clé obligatoire dans CP
- coche VF dans les options de HDO (si tu veux de la VF)
- ne coche pas VO ni MULTI ni x265 (à moins que tu veuilles que du x265)

Et ça devrait gazer...

Je regarderai quand j'aurais un peu de temps si il y a moyen de récupérer le titre FR à partir d'un titre VO pour pouvoir récupérer plus de résultats sur HDO (car pour le moment pour moi ça ne marche que si titre VO = titre FR)

**Comment by maxcore** [comment]
ouais c'est mieux ;) merci!!

**Comment by hbooo** [comment]
Hello, 

Je pense que tu peux utiliser l'api de themoviedb pour avoir le titre français : 

http://docs.themoviedb.apiary.io/#reference/movies/movieidalternativetitles/get

Beau boulot en tout cas, si jamais tu cherches d'autres idées de providers ça serait super si tu arrivais à faire un provider pour Libertalia (il y a d'ailleurs la possibilité d'afficher les titres en FR ou en VO) :)

**Comment by djoole** [comment]
Je me suis déjà débrouillé, mais sans l'API TMDB, cette dernière nécessitant une clé personnelle.

CP stocke tous les alternative titles dans sa BDD, et j'ai utilisé un module Python (langdetect) pour en sortir le titre FR :)

Pour libertalia, c'est un tracker italien non?

**Comment by hbooo** [comment]
En effet c'est plus pratique si tu passes directement par CP :)

Edit : En fait c'est bon je vois que Cyberden a déjà fait un fork avec https://github.com/cyberden/CouchPotatoServer :)

**Comment by maxcore** [comment]
@djool non fr tu veux un invite ?;)

**Comment by maxcore** [comment]
@djoole

**Comment by djoole** [comment]
Je dis pas non :)

**Comment by eucalyptus30** [comment]
Bonjour,

J'ai exactement le même problème avec Insurgent qui porte le nom "Divergente 2 : L'Insurrection" sur HDO.

La traduction française ne trouve pas bon le texte. http://i.imgur.com/33Q8i1w.png

une idée ?

**Comment by djoole** [comment]
Yes c'est un pb coté CP, qui transmet les caractères accentués mal décodés.
Je compte utiliser un autre procédé pour récupérer le titre FR, ça devrait résoudre ce genre de problème.

**Comment by eucalyptus30** [comment]
Tu comptes utiliser quoi pour le remplacer ?
Actuellement HDO ne marche pas bien :(

**Comment by djoole** [comment]
API TMDB pour récupérer le titre FR..

**Comment by eucalyptus30** [comment]
Parfait :-)
J'ai hâte de voir ça :D

**Comment by maxcore** [comment]
+1

**Comment by djoole** [comment]
Bon ben c'est pas gagné.. je viens de passer des heures à me prendre la tête sur l'encoding et j'arrive encore à la conclusion que c'est le code de CP et sa gestion moisie des encodings qui me met des batons dans les roues : le titre du film que je récupère de l'API via la fonction getJsonData() est déjà décodé, et décodé pourri, genre Les associĂŠs pour Les associés..
Du coup je peux rien en faire.
Faut que je remonte la source dans le code de CP pour voir qui me décode la foutue entrée de l'API, et modifier ce bout de code..
Si jamais quelqu'un veut donner un coup de main, n'hésitez pas!

**Comment by maxcore** [comment]
@djoole ta esseiller le nouveau couchpotato ? le branch cest : https://github.com/RuudBurger/CouchPotatoServer/tree/redesign peut-etre que le code est amelioré

**Comment by djoole** [comment]
J'ai résolu les soucis d'encoding sur le provider t411, je devrais réussir à faire la même chose pour hdo, je vais rester sur la branche master pour le moment mais merci pour l'info!

**Comment by eucalyptus30** [comment]
ça venait d'ou ?

**Comment by djoole** [comment]
En gros j'ai viré l'API allocine et utilise l'API TMDB à la place, même si le souci ne venait pas de la. M'en suis rendu compte après coup car c'est la fonction CPLog de CP qui déconne, elle affiche mal la plupart du temps les chaînes unicode accentuées, alors que la chaîne elle même est correcte.
J'ai surtout rencondé le titre en ISO-8859-1 et échappé en caractères HTML le tout avant d'envoyer la requête vers t411. Sans ça, les caractères accentués sont mal formatés et la recherche n'aboutit à rien.

Je suis en train de faire la même chose pour HDO (j'en profite pour virer langdetect et utiliser là aussi l'API TMDB pour récupérer le titre FR)

**Comment by eucalyptus30** [comment]
Du coup tu as besoin d'aide ou tu vas t'en sortir pour HDO ?

**Comment by djoole** [comment]
Ça devrait aller, par contre j'aurai besoin de testeurs une fois la modif
faite!

**Comment by djoole** [comment]
OK allez c'est fait, j'ai tout changé, va falloir tester maintenant, mais ça a l'air de tenir la route!
Je ferme cet issue, n'hésitez pas à en ouvrir d'autre pour tout problème résiduel.

**Comment by eucalyptus30** [comment]
De mon coté tout à l'air de fonctionner maintenant :-)
Hooo yeah.

**Comment by maxcore** [comment]
Cest moi ou ed tv il va pas chercher le nom fr ? En direct sur ed tv

**Comment by djoole** [comment]
Non ça marche nickel pour Ed TV : 

```
08-20 14:40:24 INFO [core.media.movie.searcher] Search for EDtv in 1080p ignoring ETA
08-20 14:40:25 DEBUG [                   hdonly] Looking on TMDB for French title of : edtv
08-20 14:40:26 DEBUG [                   hdonly] L'API TMDB a trouvé un titre français => en direct sur ed tv
08-20 14:40:27 DEBUG [                   hdonly] Searching HD-Only for en direct sur ed tv
08-20 14:40:28 DEBUG [                   hdonly] release name reported by HD-Only : en direct sur ed tv
08-20 14:40:28 DEBUG [                   hdonly] It's a match
08-20 14:40:30 DEBUG [                   hdonly] Filename is en.direct.sur.ed.tv.1999.hdtv.1080i.dts.fr.ac3.us.mkv{{{7901291342}}}
08-20 14:40:30 DEBUG [                   hdonly] Torrent added to results : id 5445; name en direct sur ed tv.1999.1080i.HDTV.AVC; detail_url https://hd-only.org/ajax.php?action=torrent&id=5445; size 7535; seeders 1; leechers 2
08-20 14:40:30 INFO [core.media.movie.searcher] Wrong: en direct sur ed tv.1999.1080i.HDTV.AVC, looking for 1080p, found ['brrip']
08-20 14:40:30 DEBUG [core.media.movie.searcher] Nothing found for EDtv in 1080p
```

**Comment by maxcore** [comment]
Ahhhh mon erreur cetait hdtv
