### ISSUE TITLE
FnT.nu !?

### ISSUE THREAD

**Issue by ghost** [djoole/couchpotato.provider.HDO#12]
Salut,
Etant donné que seul toi est actif concernant le developpement de plugins CP français, peut être aurais tu été intéressé pour développer un plug pour le fameux tracker FnT.nu ? Etant moi même utilisateur de FnT ET CP et n'étant sûrement pas le seul, est-ce que je peux te donner un éventuel coup de main concernant le site/les flux si tu n'es pas déjà membre ou à défaut, peux tu me donner quelqu'un vers qui m'orienter si l'idée ne te paraissais pas pertinente ?

Merci a toi

**Comment by djoole** [comment]
Cf. Réponse sur plugin t411

**Comment by elneruda** [comment]
Salut, je me suis inspiré du travail de djoole & de raver2046 pour créer un provider FNT : https://github.com/elneruda/couchpotato.provider.fnt

**Comment by maxcore** [comment]
@elneruda nice je test ça dans les prochaines heures ;) si tu veux un account sur libertlia fait moi signe ! jaime bien encourager les developper!

**Comment by elneruda** [comment]
@maxcore as-tu pu tester le provider ?
Je suis bien intéressé par un comte libertlia, je t'envois un mail directement.
