### ISSUE TITLE
[REQ] Ajouter une option

### ISSUE THREAD

**Issue by maxcore** [djoole/couchpotato.provider.HDO#14]
Salut djoole,

Je voulais savoir si c'étais possible de mettre une option à ton plug in HDO pour qu'il ignore 
'Required' . Si je mets rien dans required et que j'active un provider qui a de l'anglais et du français ça fou un bordel ... Si je mets french dans Required il trouve partout sauf sur HDO , dis moi si c'est possible d'avoir un option qu'on peut cocher.
Merci ;)

**Comment by djoole** [comment]
Confirme moi si j'ai bien compris : 
Dans le champ required de CP tu mets french pour t'assurer d'avoir de la VF quel que soit le provider utilisé, hors avec HDO ca trouve rien, et si tu mets rien dans required, ca trouveras du France avec HDO puisque tu as activé l'option 'VF mandatory', mais ça risque de te trouver de la VO sur les autres providers, donc tu voudrais que je fasse en sorte que HDO te trouve des trucs avec french en required, c'est bien ca?

**Comment by maxcore** [comment]
oui en plein ça mek ;) si jenleve required il trouve bien toute mes releases comme un chef je l'ai bien configurer comme tu me las montrer. Dans mes mots required :French,Multi,truchfrench,fr,VFQ,QC,MULTi-VF2

**Comment by djoole** [comment]
Ok, content d'avoir compris, mais après revue du code, je vois pas pourquoi des mots clé quels qu'ils soient dans required poseraient problème, je ne fais aucun traitement spécifique à ce sujet.
Peux-tu me mettre les logs d'un film posant problème stp?

**Comment by maxcore** [comment]
http://pastebin.com/GH9wY4Ff

**Comment by djoole** [comment]
OK j'ai compris d'ou vient le problème.
Ca vient du fait que le plugin renomme le nom de la release avant de le remonter à CP.
Il faut que je rajoute "french" au nom si une option VF a été cochée.
Vais faire ça tu me confirmera si ça marche

**Comment by djoole** [comment]
C'est fait, let me know!

**Comment by maxcore** [comment]
le french fonctionne oui ! mais pas le multi ou le VFQ . Le plug in peut lire le nom de la releases au complet ex: Terminator Genisys 2015 MULTI 1080p BluRay x264-ONLY.mkv ?

**Comment by djoole** [comment]
A la base j'avais mis au point une recomposition du nom de la release pour une bonne raison, mais je ne me souviens plus laquelle ^^.

Vais modifier le plugin pour qu'il utilise le nom de fichier on va voir ce que ça donne.. ça risque de créer des nouveaux bugs, si tu as le temps de tester ça serait cool. Je te dirai quand j'aurai fait la modif.

**Comment by djoole** [comment]
OK j'ai fait la modif, maintenant le plugin renvoie le nom de fichier auquel il a remplacé le titre FR par le titre CP pour que CP ne rejette pas le fichier. Norlamelement les infos vf, vqf, etc restent et donc on peut profiter des options required/rejected words de CP.
Je n'ai pas du tout testé, dis-moi si c'est OK!

**Comment by maxcore** [comment]
voilà c'est parfait ;)

**Comment by djoole** [comment]
J'ai refait tout un tas de modif.
En fait j'ai viré toutes les options VFF/VFQ/VO/MULTI/X265, y a plus besoin, vaut mieux utiliser les required/ignored.

Tu peux refaire un test? Pour moi ça a l'air de gazer...

**Comment by djoole** [comment]
J'ai refait un petit commit pour corriger un petit bug..

**Comment by maxcore** [comment]
thx

**Comment by maxcore** [comment]
Ça fonctionne à merveille

**Comment by djoole** [comment]
Presque... J'ai remarqué que ca deconne quand y a des apostrophes... #18
