### ISSUE TITLE
Ne fonctionne pas avec la version de sarakha63 ?

### ISSUE THREAD

**Issue by Adelscott** [djoole/couchpotato.provider.HDO#17]
J'ai changé mon fork CouchPotato de l'ancienne version de sarakha63 vers la nouvelle (persomov) et reinstallé les 2 fichiers mais je ne vois rien apparaitre dans l'interface web (qui au passage a complètement changé). 
Quelqu'un l'a testé avec la dernière version de CouchPotato ?

**Comment by maxcore** [comment]
fonctionne très bien avec la dernière version de couch

**Comment by Adelscott** [comment]
Tu pourrais up un screen du resultat sur l'interface web ?

**Comment by maxcore** [comment]
À mon retour à la maison oui

**Comment by Adelscott** [comment]
Ok en fait je suis polio, je ne créais pas le répertoire .. 
merci quand même ^^
