### ISSUE TITLE
Problème installation

### ISSUE THREAD

**Issue by Bybou** [djoole/couchpotato.provider.HDO#19]
Bonjour,
J'utilise la version 89fd4e11 (24/1/2016 10:42:44) de couchpotato depuis https://github.com/RuudBurger/CouchPotatoServer.git et je n'arrive pas à utiliser le plugin.
Je n'arrive tout simplement pas à me connecter (login et password pourtant bons) j'ai l'erreur suivante dans les logs lorsque je fais une recherche sur un film : 
02-17 15:30:18 ERROR
[edia._base.providers.base] Failed to login hdonly: unknown
02-17 15:30:18 ERROR
[edia._base.providers.base] Failed to login to: hdonly

Par ailleurs sur l'écran de setting de couchpotato voici ce que j'ai http://i.imgur.com/E5q7RMK.jpg
Nulle part on ne fait mention de x265 VFQ etc

Peut-être faut il utiliser une autre version de couchpotato ?

Merci d'avance.

**Comment by djoole** [comment]
Bonjour,

Normal pour les options, j'ai changé le plugin récemment mais ai oublié de mettre à jour le README.
Vais faire ça sous peu.

Pour ton souci, si tu es sûr et certains d'avoir saisi le bon login/passwd, il faudrait que tu actives le niveau DEBUG pour les logs et que tu redonnes les logs de la tentative d'authentification.

**Comment by Bybou** [comment]
Bonjour,

J'ai résolu mon problème de connection au tracker. Je pense que c'était lié
au certificat. J'ai dû me connecter via le browser de mon serveur
et accepte les "risques" car pas de certificat et ensuite ça a fonctionné !

En regardant de plus près le plugin je me suis aperçu qu'effectivement tout
(VFF, VFQ etc) était basé sur le nom du fichier et non les "tags" présent
sur le tracker ce qui est dommage mais je ne vois pas non plus comment
filtrer là dessus...

Le vendredi 19 février 2016, djoole notifications@github.com a écrit :

> Bonjour,
> 
> Normal pour les options, j'ai changé le plugin récemment mais ai oublié de
> mettre à jour le README.
> Vais faire ça sous peu.
> 
> Pour ton souci, si tu es sûr et certains d'avoir saisi le bon
> login/passwd, il faudrait que tu actives le niveau DEBUG pour les logs et
> que tu redonnes les logs de la tentative d'authentification.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/djoole/couchpotato.provider.HDO/issues/19#issuecomment-186333150
> .

## 

Cordialement,

_Johan Copin_

johan.copin@gmail.com jcopin@micropole.com
