### ISSUE TITLE
Erreur a l'analyse des torrent ?

### ISSUE THREAD

**Issue by Foncekar** [djoole/couchpotato.provider.HDO#2]
Bonjour(soir), j'ai l'impression que le plugin analyse plusieurs fois le même torrent :
7-21 21:35:09INFO[hpotato.core.plugins.base] Opening url: get https://hd-only.org/ajax.php?action=browse&searchstr=harry%20potter%20et%20le%20prince%20de%20sang-m%C3%AAl%C3%A9, data: []
07-21 21:35:09DEBUG[hpotato.core.plugins.base] Setting cache db176d18563f7531c4a03e1db0cff493
07-21 21:35:09DEBUG[hpotato.core.plugins.base] Waiting for hdonly, 1 seconds
07-21 21:35:10INFO[hpotato.core.plugins.base] Opening url: get https://hd-only.org/ajax.php?action=torrent&id=2235, data: []
07-21 21:35:11DEBUG[o.core.notifications.core] Cleaning messages
07-21 21:35:11DEBUG[o.core.notifications.core] Done cleaning messages
07-21 21:35:11DEBUG[hpotato.core.plugins.base] Setting cache 5e5794ca7e548ed2bcbe04dc9da00c46
07-21 21:35:11DEBUG[hpotato.core.plugins.base] Getting cache 5e5794ca7e548ed2bcbe04dc9da00c46
07-21 21:35:11DEBUG[                   hdonly] Filename is harry.potter.et.le.prince.de.sang.mele.2009.multi.1080p.vc-1.bluray.remux-only.mkv{{{22931571034}}}
07-21 21:35:11DEBUG[                   hdonly] Torrent added to results : id 2235; name Harry Potter et le Prince de Sang-M&ecirc;l&eacute;.2009.1080p.Blu-Ray Remux.VC-1; detail_url https://hd-only.org/ajax.php?action=torrent&id=2235; size 21869; seeders 0; leechers 0
07-21 21:35:11DEBUG[tato.core.plugins.quality] Found 1080p via identifier 1080p in Harry Potter et le Prince de Sang-M&ecirc;l&eacute;.2009.1080p.Blu-Ray Remux.VC-1
07-21 21:35:11DEBUG[tato.core.plugins.quality] Found bd50 via release size: 20000.0 MB < 21869.0 MB < 60000.0 MB
07-21 21:35:11DEBUG[hpotato.core.plugins.base] Setting cache [u'Harry Potter et le Prince de Sang-M&ecirc;l&eacute;.2009.1080p.Blu-Ray Remux.VC-1']
07-21 21:35:11DEBUG[hpotato.core.plugins.base] Getting cache [u'Harry Potter et le Prince de Sang-M&ecirc;l&eacute;.2009.1080p.Blu-Ray Remux.VC-1']
07-21 21:35:11INFO[core.media.movie.searcher] Wrong: "Harry Potter et le Prince de Sang-M&ecirc;l&eacute;.2009.1080p.Blu-Ray Remux.VC-1" is too large to be BR-Rip. 21869MB instead of the maximum of 7000MB.
07-21 21:35:11DEBUG[hpotato.core.plugins.base] Getting cache cf748b0ea97221a562cb09875107efec
07-21 21:35:27DEBUG[                   hdonly] movie titles : [u'harry potter et le prince de sang-m\xeal\xe9', u'harry potter et le prince de sang m\xeal\xe9', u'harry potter 6 le prince de sang m\xeal\xe9', u'harry potter 6 - et le prince de sang m\xeal\xe9', u'harry potter - 6 - le prince de sang m\xeal\xe9', u'harry potter 6 et le prince de sang-m\xeal\xe9', u'harry potter et le prince de sang-m\xeal\xe9', u'harry potter and the half-blood prince', u'harry potter vi and the half-blood prince', u'harry potter 6 - the half-blood prince', u'harry potter vi - the half-blood prince', u'harry potter 6 the half-blood prince', u'harry potter - 6 - the half-blood prince']
07-21 21:35:27DEBUG[                   hdonly] Searching HD-Only for harry potter et le prince de sang-m�l�
07-21 21:35:27DEBUG[hpotato.core.plugins.base] Getting cache db176d18563f7531c4a03e1db0cff493
07-21 21:35:27DEBUG[hpotato.core.plugins.base] Getting cache 5e5794ca7e548ed2bcbe04dc9da00c46
07-21 21:35:27DEBUG[hpotato.core.plugins.base] Getting cache 5e5794ca7e548ed2bcbe04dc9da00c46
07-21 21:35:27DEBUG[                   hdonly] Filename is harry.potter.et.le.prince.de.sang.mele.2009.multi.1080p.vc-1.bluray.remux-only.mkv{{{22931571034}}}
07-21 21:35:27DEBUG[                   hdonly] Torrent added to results : id 2235; name Harry Potter et le Prince de Sang-M&ecirc;l&eacute;.2009.1080p.Blu-Ray Remux.VC-1; detail_url https://hd-only.org/ajax.php?action=torrent&id=2235; size 21869; seeders 0; leechers 0
07-21 21:35:27DEBUG[hpotato.core.plugins.base] Getting cache [u'Harry Potter et le Prince de Sang-M&ecirc;l&eacute;.2009.1080p.Blu-Ray Remux.VC-1']
07-21 21:35:27DEBUG[hpotato.core.plugins.base] Getting cache [u'Harry Potter et le Prince de Sang-M&ecirc;l&eacute;.2009.1080p.Blu-Ray Remux.VC-1']
07-21 21:35:27INFO[core.media.movie.searcher] Wrong: "Harry Potter et le Prince de Sang-M&ecirc;l&eacute;.2009.1080p.Blu-Ray Remux.VC-1" is too large to be BR-Rip. 21869MB instead of the maximum of 7000MB.
07-21 21:35:27DEBUG[hpotato.core.plugins.base] Getting cache cf748b0ea97221a562cb09875107efec
07-21 21:35:41DEBUG[                   hdonly] movie titles : [u'harry potter et le prince de sang-m\xeal\xe9', u'harry potter et le prince de sang m\xeal\xe9', u'harry potter 6 le prince de sang m\xeal\xe9', u'harry potter 6 - et le prince de sang m\xeal\xe9', u'harry potter - 6 - le prince de sang m\xeal\xe9', u'harry potter 6 et le prince de sang-m\xeal\xe9', u'harry potter et le prince de sang mele', u'harry potter and the half-blood prince', u'harry potter vi and the half-blood prince', u'harry potter 6 - the half-blood prince', u'harry potter vi - the half-blood prince', u'harry potter 6 the half-blood prince', u'harry potter - 6 - the half-blood prince']
07-21 21:35:41DEBUG[                   hdonly] Searching HD-Only for harry potter et le prince de sang-m�l�
07-21 21:35:41DEBUG[hpotato.core.plugins.base] Getting cache db176d18563f7531c4a03e1db0cff493
07-21 21:35:41DEBUG[hpotato.core.plugins.base] Getting cache 5e5794ca7e548ed2bcbe04dc9da00c46
07-21 21:35:41DEBUG[hpotato.core.plugins.base] Getting cache 5e5794ca7e548ed2bcbe04dc9da00c46
07-21 21:35:41DEBUG[                   hdonly] Filename is harry.potter.et.le.prince.de.sang.mele.2009.multi.1080p.vc-1.bluray.remux-only.mkv{{{22931571034}}}
07-21 21:35:41DEBUG[                   hdonly] Torrent added to results : id 2235; name Harry Potter et le Prince de Sang-M&ecirc;l&eacute;.2009.1080p.Blu-Ray Remux.VC-1; detail_url https://hd-only.org/ajax.php?action=torrent&id=2235; size 21869; seeders 0; leechers 0
07-21 21:35:41DEBUG[hpotato.core.plugins.base] Getting cache [u'Harry Potter et le Prince de Sang-M&ecirc;l&eacute;.2009.1080p.Blu-Ray Remux.VC-1']
07-21 21:35:41DEBUG[hpotato.core.plugins.base] Getting cache [u'Harry Potter et le Prince de Sang-M&ecirc;l&eacute;.2009.1080p.Blu-Ray Remux.VC-1']
07-21 21:35:41INFO[core.media.movie.searcher] Wrong: "Harry Potter et le Prince de Sang-M&ecirc;l&eacute;.2009.1080p.Blu-Ray Remux.VC-1" is too large to be BR-Rip. 21869MB instead of the maximum of 7000MB.

Pourtant en regardant le retour de : 
https://hd-only.org/ajax.php?action=browse&searchstr=harry%20potter%20et%20le%20prince%20de%20sang-m%C3%AAl%C3%A9

Il y a plusieurs torentID j'ai loupé un truc ?

**Comment by Foncekar** [comment]
Après avoir regarder tout ça de plus près il semblerais que seul le premier torrent est analysé a chaque fois.

**Comment by eucalyptus30** [comment]
Bonjour !

J'ai le même problème que toi.

Il script analyse uniquement le premier resultat.

**Comment by Foncekar** [comment]
Je ne me servais pas de HDO avant, tu sais s'il y a eut une modification au niveau du site ?
Avant tout les resultats étaient bien parsés ?

**Comment by Foncekar** [comment]
Je pense que ça viens d'ici : 
for torrent in data['response']['results'][0]['torrents']:

**Comment by djoole** [comment]
Bonjour,
Je vais voir pourquoi ça ne checke pas les autres torrents, ça devrait marcher. 
Par contre je n'ai pas le temps en ce moment, donc merci d'être patient car je suis tout seul à maintenir ce provider :)

**Comment by Foncekar** [comment]
Salut, a tout hasard tu n'as pas un ancien JSON sous le bras pour voir ce qui aurait changer ? Si je peux aider a quelques chose ^^ même si le parsing python c'est pas mon fort.

**Comment by eucalyptus30** [comment]
Du coup, j'y ai jeté un œil.
Je t'ai fait un commit : https://github.com/djoole/couchpotato.provider.HDO/pull/3
ça devrait être bon après ça.

Par contre il manque une boucle à ce niveau "data['response']['results']".
Car il y a data['response']['results'][0] mais il peut y avoir plusieurs films qui correspondent à la recherche. Mais ça doit être un cas extrêmement rare.

**Comment by eucalyptus30** [comment]
Par contre, comment faire coexister ce plug-in avec T411.
Car j'ai ajouté "french, truefrench" en required pour que sur T411, il n'y ait que du Français.
Mais du coup, ça bloque sur HD-ONLY à cause de ça maintenant... :-(
"Wrong: Required word missing"

**Comment by Foncekar** [comment]
La modif fonctionne nickel ;) 
Le plus simple serait peut-être de modifier le plug-in t411 en ajoutant une option dans les réglages "only fr"
qui verifierais dans le nom la presence de french turefrench ect nan ?

**Comment by Foncekar** [comment]
Par contre maintenant je me retrouve avec des erreurs: " undetermined naming"

 Wrong: Harry Potter et le Prince de Sang-M&ecirc;l&eacute;.2009.1080p.Blu-Ray Rip.x264, undetermined naming. Looking for 'Harry Potter et le prince de sang-mêlé (2009)'

Problème au niveau des caractères speciaux (accent) ?

**Comment by eucalyptus30** [comment]
pour moi le problème vient de " (2009)" dans le titre de ton film.

**Comment by Foncekar** [comment]
![erreur](https://cloud.githubusercontent.com/assets/7449746/8848193/bd931e3e-3135-11e5-9e0c-993730750a36.png)
Quand je regarde le log j'ai un petit doute.

**Comment by eucalyptus30** [comment]
haha en effet. peut être l'html qui pose problème.

**Comment by djoole** [comment]
Hello, vraiment pas le temps de me pencher sur tout ça, j'ai fait confiance et commité la modif d'@eucalyptus30 :)

Pour la problématique t411 : CP en confit de base à french et truefrench en mots interdit (et ça me va très bien vu que je suis VO lover).
Mais pour que je puisse récupérer des films FR sur HDO j'ai du bidouiller et faire en sorte de virer du nom de fichier les mentions french truefrench avant de le passer à CP afin que ce dernier n'écarte pas la release.
Mais du coup, pour toi qui a mis ces mots en requis et pas interdit, ça pose problème.

Le seul truc que je vois est rajouter une option dans le prov HDO "french truefrench requis", qui ferait que le prov vire pas ces mots si l'option est activée.

Mais pas le temps de faire ça de mon côté, sorry...

**Comment by eucalyptus30** [comment]
Pas de problème.

**Comment by Foncekar** [comment]
Le problème des accents semble asse simple : 
C'est au niveau de l'encodage et de  "release_name" , j'ai pas vraiment eut le temps de me pencher dessus, juste fait un petit test non concluant en ajoutant
                release_name_clean = str(release_name.encode("latin-1"))
                log.debug('release_name_clean : %s' % release_name_clean)

**Comment by djoole** [comment]
Hello, le pb d'accents devrait être résolu avec le dernier commit.
C'était un pb de décodage de caractères HTML exactement :)
Merci de me confirmer pour que je puisse clore l'issue

**Comment by djoole** [comment]
#4
