### ISSUE TITLE
Doesn't find movie on hdonly because it doesn't use file name

### ISSUE THREAD

**Issue by Adelscott** [djoole/couchpotato.provider.HDO#20]
### Steps to reproduce:
1. Why are the words "the revenant 2015 1080p blu ray rip x264" used for search instead of file name "the.revenant.2015.rerip.multi.1080p.bluray.dts-hdma.x264-only.mkv" ? It doesn't find "dts", the unique word I tried in "required words" ....
2. Looking at json result, I don't know how the list "the revenant 2015 1080p blu ray rip x264"  is made ..
### Information:

Movie(s) I have this with: ...
Quality of the movie being searched: 1080p
Providers I use: hdonly
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 89fd4e11 (2016-01-24 10:42:44)
Running on: synology
### Logs:

```
04-14 00:24:21 DEBUG [                   hdonly] Filename is the.revenant.2015.rerip.multi.1080p.bluray.dts-hdma.x264-only.mkv{{{22353612674}}} 
04-14 00:24:21 DEBUG [                   hdonly] Torrent added to results : id 9990; name the revenant.2015.1080p.Blu-Ray Rip.x264; detail_url https://hd-only.org/ajax.php?action=torrent&id=9990; size 21318; seeders 52; leechers 10 
04-14 00:24:21 INFO [core.media._base.searcher] Wrong: Required word missing: the revenant 2015 1080p blu ray rip x264 
```

**Comment by djoole** [comment]
Fixed that since january. git pull is your friend ;)

**Comment by Adelscott** [comment]
thanks, mine was from 5th december ... forgot that I had to pull it manually
