### ISSUE TITLE
CP trouve mais ne télécharge pas.

### ISSUE THREAD

**Issue by CooperBarrett** [djoole/couchpotato.provider.HDO#21]
Salut,

Je ne sais pas si le repo est toujours supporté mais je tente ma chance.

Alors voilà, j'ai bien installé le provider mais j'ai quelques soucis pour le faire fonctionner.

Par exemple, pour "Les Lyonnais" en 720p, voici ce que me mettent les logs : 

```
[core.media.movie.searcher] Search for Les Lyonnais in 720p
06-14 23:22:47 INFO[hpotato.core.plugins.base] Opening url: get http://mondomaine.myqnapcloud.com:9117/potato/abnormal?imdbid=tt1741542&user=&passkey=xxx
06-14 23:22:47 INFO[hpotato.core.plugins.base] Opening url: get https://hd-only.org/ajax.php?action=index, data: []
06-14 23:22:48 INFO[hpotato.core.plugins.base] Opening url: get https://api.themoviedb.org/3/search/movie?api_key=xxx&language=fr&query=les%20lyonnais, data: []
06-14 23:22:49 INFO[hpotato.core.plugins.base] Opening url: get http://mondomaine.myqnapcloud.com:9117/potato/xthor?imdbid=tt1741542&user=&passkey=xxx
06-14 23:22:49 INFO[hpotato.core.plugins.base] Opening url: get https://hd-only.org/ajax.php?action=browse&searchstr=les%20lyonnais, data: []
06-14 23:22:51 INFO[hpotato.core.plugins.base] Opening url: get https://hd-only.org/ajax.php?action=torrent&id=1658, data: []
06-14 23:22:52 INFO[hpotato.core.plugins.base] Opening url: get https://hd-only.org/ajax.php?action=torrent&id=3025, data: []
06-14 23:22:52 INFO[core.media.movie.searcher] Wrong: les lyonnais 720p x264 vo dts dxva-hdz.mkv{{{5162204354}}}, undetermined naming. Looking for 'Les Lyonnais (2011)'
06-14 23:22:53 INFO[hpotato.core.plugins.base] Opening url: get https://hd-only.org/ajax.php?action=torrent&id=10124, data: []
```

Comme on peut le voir, il me trouve bien le film : 

`06-14 23:22:52 INFO[hpotato.core.plugins.base] Opening url: get https://hd-only.org/ajax.php?action=torrent&id=3025, data: []` ==> l'ID correspond bien à la release recherché

Mais ensuite il me met cette erreur : 

`06-14 23:22:52 INFO[core.media.movie.searcher] Wrong: les lyonnais 720p x264 vo dts dxva-hdz.mkv{{{5162204354}}}, undetermined naming. Looking for 'Les Lyonnais (2011)'`

`undetermined naming` c'est assez clair mais je ne vois pas comment résoudre ce problème.

Voilà ou j'en suis. Pour info, voici mes réglages : 

Global Filters (j'ai retiré french et truefrench): 
![](https://lut.im/3b1ggrui1H/aqLc3UiDnzz59qxo.png)

Et ma catégorie HD Français : 
![](https://lut.im/uxjK5rIsnf/B0E6tIhJJRYH2Hfo.png)
A savoir que le problème existe que je mette **Category HD Français** ou **No Category**

Pour les autres lignes de logs, c'est que j'utilise également jackett (qui ne me trouve rien non plus car il me cherche les titres en anglais...)

Voilà c'est déjà pas mal, j'espère trouver de l'aide ici. 

Merci d'avance pour ton aide.

**Comment by djoole** [comment]
Hello, avec la category HD Français c'est normal que ça ne marche pas, tu as géré french en tant que mot clé requis, alors que ce dernier n'est pas dans le nom du fichier.

Si tu n'utilises pas de catégorie, ça ne marche quand même pas car CP cherche la date entre parenthèses alors qu'elle n'y est pas dans le nom du fichier.

C'est ça le problème des porteurs qui ne respectent pas les règles de dommage des fichiers.

Donc pour ton problème, il faut cocher l'option "ignore year" au niveau du provider, ça devrait faire le job.
Tiens-moi au courant.

**Comment by CooperBarrett** [comment]
Désolé de la réponse tardive, je n'avait pas vu la notification...
C'est OK, ça fonctionne avec "ignore year"

Je te remercie, je clos l'issue
