### ISSUE TITLE
Problème de script ?

### ISSUE THREAD

**Issue by Adelscott** [djoole/couchpotato.provider.HDO#22]
### Steps to reproduce:
1. search :)
### Information:

Movie(s) I have this with: ...
Quality of the movie being searched: ...
Providers I use: ...
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 89fd4e11 (2016-01-24 10:42:44)
Running on: ...
### Logs:

```
09-08 22:35:47 ERROR [                   hdonly] #### Failed to parse TMDB API: Traceback (most recent call last):
  File "/usr/local/couchpotatoserver-custom/var/custom_plugins/hdonly/main.py", line 142, in getFrenchTitle
    if data['results'] != None:
TypeError: list indices must be integers, not str

```

**Comment by djoole** [comment]
Duplicate https://github.com/djoole/couchpotato.provider.t411/issues/25
