### ISSUE TITLE
amélioration recherche release

### ISSUE THREAD

**Issue by danylich** [djoole/couchpotato.provider.HDO#5]
### Steps to reproduce:
1. Rechercher Mad max

problème constaté:
- la recherche "Mad Max" sous HD-Only retourne plusieurs résultats (Mad Max, Mad Max2, Mad Max: fury road, ...) avec des qualités différentes. Le problème est que le provider s'arrête au premier résultat trouvé : Mad Max: fury road donc la release est rejeté car ce n'est pas le bon nom de film

Correction souhaitée:
- Le provider ne s'arrête pas à la première release trouvée. Ce serait bien qu'il continue aussi jusqu'à trouver la bonne qualité ( par exemple: si la qualité recherchée est 1080p et que la première release est BRRip, il passe à la deuxième release et ainsi de suite)
### Information:

Movie(s) I have this with: Mad Max
Quality of the movie being searched: 1080p
Providers I use: Hdonly
Version of CouchPotato: git:(RuudBurger:CouchPotatoServer master) 69825f9d (2015-05-27 14:06:41)
Running on: Synology
### Logs:

```
07-25 23:29:17  INFO [ie.providers.info.omdbapi] Found: Mad Max (1979) 
07-25 23:29:17 DEBUG [   couchpotato.core.event] Return modified results for movie.info 
07-25 23:29:17 DEBUG [to.core.media.movie._base] Adding titles: [u'Mad Max', u'Mad Max 1', u'Interceptor', u'Mad Max - Interceptor', u'\u0411\u0435\u0437\u0443\u043c\u043d\u044b\u0439 \u041c\u0430\u043a\u0441', u'Mad Max - Salvajes de autopista'] 
07-25 23:29:17  INFO [hpotato.core.plugins.base] Opening url: get http://ia.media-imdb.com/images/M/MV5BMTM4Mjg5ODEzMV5BMl5BanBnXkFtZTcwMDc3NDk0NA@@._V1_.jpg, data: [] 
07-25 23:29:18 DEBUG [hpotato.core.plugins.base] Releasing lock: media.get.e13b338bc866491ea6d22ef4051de604 
07-25 23:29:18 DEBUG [to.core.media._base.media] Changing status for Mad Max 
07-25 23:29:18  INFO [hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/eta/tt0079501/, data: [] 
07-25 23:29:18 DEBUG [hpotato.core.plugins.base] Setting cache c5c453f9f2f5efda6b37fe36ee97ec3e 
07-25 23:29:18 DEBUG [iders.info.couchpotatoapi] Found ETA for tt0079501: {u'dvd': 1147730400, u'expires': 1439384223, u'theater': 1138921200, u'bluray': True} 
07-25 23:29:18 DEBUG [o.core.notifications.core] Notifying frontend 
07-25 23:29:18 DEBUG [o.core.notifications.core] Done notifying frontend 
07-25 23:29:18  INFO [core.media.movie.searcher] Search for Mad Max in 1080p ignoring ETA 
07-25 23:29:18 DEBUG [hpotato.core.plugins.base] Getting cache cf748b0ea97221a562cb09875107efec 
07-25 23:29:18 DEBUG [o.core.notifications.core] Getting messages with id: 422910c1-b47c-4572-b8c8-0d20375f0d21 
07-25 23:29:18 DEBUG [o.core.notifications.core] Returning for 422910c1-b47c-4572-b8c8-0d20375f0d21 1 messages 
07-25 23:29:18 DEBUG [o.core.notifications.core] Getting messages with id: 422910c1-b47c-4572-b8c8-0d20375f0d21 
07-25 23:29:18 DEBUG [o.core.notifications.core] Returning for 422910c1-b47c-4572-b8c8-0d20375f0d21 1 messages 
07-25 23:29:18 DEBUG [o.core.notifications.core] Getting messages with id: 422910c1-b47c-4572-b8c8-0d20375f0d21 
07-25 23:29:18 DEBUG [o.core.notifications.core] Returning for 422910c1-b47c-4572-b8c8-0d20375f0d21 1 messages 
07-25 23:29:20 DEBUG [o.core.notifications.core] Getting messages with id: ea78eb1f-200c-408f-ae04-0ab13c491fc3 
07-25 23:29:20 DEBUG [o.core.notifications.core] Returning for ea78eb1f-200c-408f-ae04-0ab13c491fc3 0 messages 
07-25 23:29:20 DEBUG [o.core.notifications.core] Getting messages with id: ea78eb1f-200c-408f-ae04-0ab13c491fc3 
07-25 23:29:20 DEBUG [o.core.notifications.core] Returning for ea78eb1f-200c-408f-ae04-0ab13c491fc3 0 messages 
07-25 23:29:20 DEBUG [o.core.notifications.core] Getting messages with id: ea78eb1f-200c-408f-ae04-0ab13c491fc3 
07-25 23:29:20 DEBUG [o.core.notifications.core] Returning for ea78eb1f-200c-408f-ae04-0ab13c491fc3 0 messages 
07-25 23:29:21 DEBUG [                   hdonly] movie titles : ['mad max'] 
07-25 23:29:21 DEBUG [                   hdonly] Searching HD-Only for mad max 
07-25 23:29:21  INFO [hpotato.core.plugins.base] Opening url: get https://hd-only.org/ajax.php?action=browse&searchstr=mad%20max, data: [] 
07-25 23:29:22 DEBUG [hpotato.core.plugins.base] Setting cache ae488c31519930e08b67b3ac184d98df 
07-25 23:29:22 DEBUG [hpotato.core.plugins.base] Getting cache 6c0e3a3d8aa336883238326d5e000571 
07-25 23:29:22 DEBUG [hpotato.core.plugins.base] Getting cache 6c0e3a3d8aa336883238326d5e000571 
07-25 23:29:22 DEBUG [                   hdonly] Filename is mad.max.fury.road.2015.vostfr.1080p.web-dl.ac3.x264-fureton.mkv{{{4360675829}}} 
07-25 23:29:22 DEBUG [                   hdonly] Torrent added to results : id 4695; name Mad Max: Fury Road.2015.1080p.Web-DL/Rip.x264; detail_url https://hd-only.org/ajax.php?action=torrent&id=4695; size 4158; seeders 65; leechers 0 
07-25 23:29:22 DEBUG [hpotato.core.plugins.base] Getting cache [u'Mad Max: Fury Road.2015.1080p.Web-DL/Rip.x264'] 
07-25 23:29:22  INFO [core.media.movie.searcher] Wrong: Mad Max: Fury Road.2015.1080p.Web-DL/Rip.x264, looking for 1080p, found ['brrip'] 
07-25 23:29:22 DEBUG [core.media.movie.searcher] Nothing found for Mad Max in 1080p 
07-25 23:29:22 DEBUG [o.core.notifications.core] Notifying frontend 
```

Résultat recherche "Mad Max" sur HD-only
Mad Max: Fury Road [2015] [Film]    Favoris
4 semaines  4.06 GB (Max)   190 65  0
− Web-DL/Rip
[ T | S ] » x264 / 1080p / VO / stFR   1   4 semaines  4.06 GB 190 65  0
Mad Max au-delà du dôme du tonnerre [1985] [Film] Favoris
2 mois  28.60 GB (Max)  92  23  0
− Blu-Ray
[ T | S ] » AVC / 1080p / VO / stFR / VFI  7 mois  28.60 GB    23  6   0
− Blu-Ray Remux
[ T | S ] » AVC / 1080p / VO / stFR / VFI /    1   2 mois  24.03 GB    26  6   0
− Blu-Ray Rip
[ T | S ] » x264 / 1080p / VO / stFR / VFI /   1   2 mois  13.66 GB    43  11  0
Mad Max 2 le Défi [1981] [Film]    Favoris
2 mois  23.75 GB (Max)  128 27  0
− Blu-Ray
[ T | S ] » AVC / 1080p / VO / stFR / VFI  7 mois  23.75 GB    28  6   0
− Blu-Ray Remux
[ T | S ] » AVC / 1080p / VO / stFR / VFI /    1   2 mois  18.75 GB    37  5   0
− Blu-Ray Rip
[ T | S ] » x264 / 1080p / VO / stFR / VFI /   1   2 mois  10.68 GB    63  16  0
Mad Max [1979] [Film]   Favoris
2 mois  21.49 GB (Max)  128 23  0
− Blu-Ray
[ T | S ] » AVC / 1080p / VO / stFR / VFI  7 mois  21.49 GB    27  4   0
− Blu-Ray Remux
[ T | S ] » AVC / 1080p / VO / stFR / VFI /    1   2 mois  17.51 GB    44  8   0
− Blu-Ray Rip
[ T | S ] » x264 / 1080p / VO / stFR / VFI /   1   2 mois  9.43 GB 57  11  0

**Comment by djoole** [comment]
Hello, tu as synchro ton repo? J'ai commité hier un dix pour la boucle de recherche qui était cassée.

**Comment by djoole** [comment]
fix pas dix ;-)

**Comment by danylich** [comment]
Je viens de le faire !
si je cherche mad max, il me trouve toujours fury road en premier et passe pas aux autres résultats. De plus, il ne me le télécharge pas car c'est pas la qualité demandé alors qu'il devrait ne pas me le télécharger car c'est pas le bon film. Enfin à voir si il vérifie pas la qualité du film avant le nom.

Sinon pour la qualité, ton fix corrige bien le problème !

**Comment by danylich** [comment]
Salut,

Je viens de la faire !

Résultat: si je cherche mad max, il me trouve toujours fury road (et passe
pas aux autres résultats ) mais il ne me le télécharge pas car c'est pas la
qualité demandé alors qu'il devrait ne pas me le télécharger car c'est pas
le bon film. Enfin à voir si il vérifie pas la qualité du film avant le nom.

Pour '71, toujours la même chose

Par contre, j''ai l'impression qu'il passe bien à une autre release si la
qualité ne lui convient pas (confimé : il m'a téléchargé le roi lion \o/).
Mais ça fait chier les accents, c'est ce qui me bloque un max. J'ai presque
tous mes films avec des accents :-(

Je t'ai aussi mis un petit comment sur github ! Tu es sur la bonne voie ;-)

Dany

2015-07-25 23:52 GMT+02:00 djoole notifications@github.com:

**Comment by djoole** [comment]
Vient de passer ma soirée sur ce bordel, mais je pense que c'est bon maintenant.. avant de chercher les torrents, il checke tous les résultats et choisi celui qui fait partie des titres de CP.
Dis-moi si ça gaze!

**Comment by maxcore** [comment]
@djoole ca marche parfaitement mais je dois virer les mots requis ? 'VFF, FRENCH, VFQ, TRUEFRENCH' ca j'ai pas le choix de mettre vu que jai d'autre provider .... FNT, LIBERTALIA....

**Comment by djoole** [comment]
Comme j'expliquais plus haut (ou dans un autre issue), mon provider est fait pour fonctionner avec une config standard qui interdit le mot french.
Si chez toi ce mot est en requis et que tu ne peux faire autrement, il faudrait que je rajoute une option pour gérer ce cas.
