### ISSUE TITLE
Configuration HD-Only

### ISSUE THREAD

**Issue by maxcore** [djoole/couchpotato.provider.HDO#8]
@djoole 

1-C'est pas un bug gênant mais je voulais juste savoir si c'étais normal (Voir Photo) Que la case Password soit en haut et le User Name et plus bas ? Simple question .

2- 

Je sais pas si c'est moi qui lis mal l'anglais mais si je coche VFQ il ignore le VFQ mais pourtant C'est écrit si vous voulez la track VFQ coche la case . Pour le x265 c'est bien écrit que si on coche la case ça va ignorer les releases x265 et je vois bien dans la console qu'il l'est ignore.

![capture d ecran 2015-08-19 22 26 33](https://cloud.githubusercontent.com/assets/4043787/9391255/b84c7d16-4743-11e5-8678-3b189b5184eb.png)

**Comment by djoole** [comment]
Hello,
1. Je n'ai pas le souci chez moi.. les options sont affichées dans l'ordre du code : 
   https://github.com/djoole/couchpotato.provider.HDO/blob/master/hdonly/__init__.py
   <img width="771" alt="cp" src="https://cloud.githubusercontent.com/assets/1114842/9394959/a4597f28-478b-11e5-8b0d-9932091139c5.png">
   Essaie de faire un CTRL-R pour rafraichir l'affichage des options.
2. Oui, normalement si "VFQ Mandatory" (mandatory veut dire obligatoire) est coché, ça devrait te récupérer que des release dont le nom de fichier contient 'vfq'
   Peux-tu me donner un nom de film? Je ferai l'essai, je t'avoue ne pas avoir validé le fonctionnement de cette option car je ne récupère que de la VO.

Pour le x265, non, l'option est mandatory aussi, donc ça veut dire que si on coche "X265 Mandatory", ça ne récupèrera que des releases dont le nom de fichier contient 'x265' (ça devrait marcher, je l'avais validé)

**Comment by maxcore** [comment]
ok pour le #1 c'est Chrome qui fait ça car je viens de tester avec firefox et ça fonctione

#2 

j'ai cocher tout les case sauf le x265
pour le film : Divergente 2 : L'Insurrection 

```
08-20 17:14:28 DEBUG [                   hdonly] Filename is insurgent.2015.multi.truefrench.1080p.bluray.remux.avc-bdhd.mkv{{{22535059699}}}
08-20 17:14:28 DEBUG [                   hdonly] VFQ mandatory checked, ignoring torrent 5261
08-20 17:14:28 DEBUG [                   hdonly] Filename is insurgent.2.2015.3d.vfq.top.bottom.1080p.bluray.x264.ac3.5.1-h72-3d.mkv{{{9181359345}}}
08-20 17:14:28 DEBUG [                   hdonly] VF mandatory checked, ignoring torrent 5153
08-20 17:14:28 DEBUG [                   hdonly] Filename is divergente 2 l'insurrection 2015 multi 1080p bluray x264-only.mkv{{{16591311818}}}
08-20 17:14:28 DEBUG [                   hdonly] VFQ mandatory checked, ignoring torrent 5443
08-20 17:14:28 DEBUG [                   hdonly] Filename is divergente 2 l'insurrection 2015 multi 720p bluray x264-only.mkv{{{6911833014}}}
08-20 17:14:28 DEBUG [                   hdonly] VFQ mandatory checked, ignoring torrent 5442

```

si je comprends bien avec les langues je dois en cocher une seul si je veux avoir le résultat .

donc pour moi si je veux être sur d'avoir une releases je coche rien.

**Comment by djoole** [comment]
tu coches la langue qui est obligatoire pour toi.
Donc si tu n'as aucune préférence tu coches rien en effet :)
Du coup y a un vrai pb avec le vfq ou je peux clore?

**Comment by maxcore** [comment]
Oui tu peux closer ;)
