### ISSUE TITLE
Intégrer les providers FR dans la nouvelle mouture de RuudBurger

### ISSUE THREAD

**Issue by fana13** [djoole/couchpotato.provider.HDO#9]
Salut et merci djoole pour ton taf, c'est vraiment parfait !!
Je viens de tester la nouvelle mouture de RuudBurger et c'est vraiment beau !
J'ai réussi à intégrer tes deux providers facilement et c'est tout à fait opérationnel, par contre je n'arrive pas à intégrer les autres (FNT, Libertalia, FTDB, CPasBien).
Je me suis uniquement concentré sur FNT pour le moment mais mes connaissances sont beaucoup trop limitées pour arriver à faire quoi que ce soit.
Tu pense que tu pourrais tenter le coup ?
Merci.

**Comment by djoole** [comment]
Hello, je pense faire FNT, par contre je n'aime pas trop Libertalia, FTDB je suis pas inscrit, et cpasbien à que de la SD, je regarde que de la HD.

Bref j'essaierai de faire un provider pour FTDB mais je ne peux pas dire quand je vais m'y mettre, donc va falloir être patient ;-)

**Comment by fana13** [comment]
Parfait, c'est mon préféré en plus :pCpasbien et FTDB je t'avouerai que je m'en cogne mais c'est plus pour les autres à qui cela peut profiter que je me suis permis de t'en faire la demande.En tout cas merci pour ta réponse et encore merci pour ton taf !

Date: Sat, 29 Aug 2015 07:53:18 -0700

**Comment by 4LEXE** [comment]
Bonjour,

cpasbien fait de la HD , c'est dommage ... Et  n'avoir que t411 comme provider français c'est encore plus dommage.
